from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name= 'home'),
    path('about/', views.about, name= 'about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
    path('attachee/', views.attachee_list, name='attachee_list'),
    path('view_attachments/', views.view_attachments, name='view_attachments'),
    path('visited_posts/', views.visited_posts, name='visited_posts'),
    path('book_room/<int:room_id>/', views.book_room, name='book_room'),
    path('all_houses/', views.all_houses, name='all_houses'),
    path('house/<int:house_id>/review/', views.submit_house_review, name='submit_house_review'),
    path('company/<int:company_id>/review/', views.submit_company_review, name='submit_company_review'),
    path('all_attachment_posts/', views.all_attachment_posts, name='all_attachment_posts'),
    path('dashboard/admin/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/attachee/', views.attachee_dashboard, name='attachee_dashboard'),
    path('dashboard/company/', views.company_dashboard, name='company_dashboard'),
    path('dashboard/tenants/', views.tenants_dashboard, name='tenants_dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('dashboard/', views.dashboard_router, name='dashboard'),
    path('post_house/', views.post_house, name='post_house'),
    path('my_houses/', views.my_houses, name='my_houses'),
    path('house/<int:house_id>/', views.house_detail, name='house_detail'),
    path('house/<int:house_id>/edit/', views.edit_house, name='edit_house'),
    path('house/<int:house_id>/delete/', views.delete_house, name='delete_house'),
    path('view_houses/', views.view_houses, name='view_houses'),
    path('my_posts/', views.my_attachment_posts, name='my_attachment_posts'),
    path('attachment/<int:attachment_id>/edit/', views.edit_attachment, name='edit_attachment'),    
    path('attachment/<int:attachment_id>/delete/', views.delete_attachment, name='delete_attachment'),
    path('view_applicants', views.view_applicants, name='view_applicants'),
    path('post_attachment/', views.post_attachment, name='post_attachment'),
    path('my_bookings/', views.my_bookings, name='my_bookings'),
    path('my_bookings/cancel/<int:booking_id>/', views.cancel_booking, name='cancel_booking'),
    path('submit_feedback/', views.submit_feedback, name='submit_feedback'),
    path('feedback_list/', views.feedback_list, name='feedback_list'),
    path('feedback/<int:feedback_id>/delete/', views.delete_feedback, name='delete_feedback'),
    path('booking/<int:booking_id>/cancel/', views.cancel_booking, name='cancel_booking'),
    path('booking/<int:booking_id>/delete/', views.delete_booking, name='delete_booking'),
    path('bookings/delete-past/', views.delete_past_bookings, name='delete_past_bookings'),
    path('bookings/<int:booking_id>/edit/', views.edit_booking, name='edit_booking'),
    path('booking/<int:booking_id>/approve', views.approve_booking, name='approve_booking'),
    path('view_ booked_rooms/', views.view_booked_rooms, name='view_booked_rooms'),
    path('tenant/bookings', views.tenant_house_bookings, name='tenant_house_bookings'),
    ]