from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name= 'home'),
    path('about/', views.about, name= 'about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
    path('attachee/', views.attachee_list, name='attachee_list'),
    path('apply_attachment/<int:attachment_id>/', views.apply_attachment, name='apply_attachment'),
    path('view_attachments/', views.view_attachments, name='view_attachments'),
    path('my_applications/', views.my_applications, name='my_applications'),
    path('book_rental/<int:rental_id>/', views.book_rental, name='book_rental'),
    path('all_rentals/', views.all_rentals, name='all_rentals'),
    path('all_attachment_posts', views.all_attachment_posts, name='all_attachment_posts'),
    path('dashboard/admin/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/attachee/', views.attachee_dashboard, name='attachee_dashboard'),
    path('dashboard/company/', views.company_dashboard, name='company_dashboard'),
    path('dashboard/tenants/', views.tenants_dashboard, name='tenants_dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('dashboard/', views.dashboard_router, name='dashboard'),
    path('post_rental/', views.post_rental, name='post_rental'),
    path('make_inquiry/', views.make_inquiry, name='make_inquiry'),
    path('view_rentals/', views.view_rentals, name='view_rentals'),
    path('opportunites/', views.opportunities, name='opportunities'),
    path('view_applicants', views.view_applicants, name='view_applicants'),
    path('post_attachment/', views.post_attachment, name='post_attachment'),
    path('my_bookings/', views.my_bookings, name='my_bookings'),
]