# Generated by Django 6.0.5 on 2026-06-01 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_deadline', models.DateField(auto_created=True)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('slots', models.IntegerField()),
                ('application_link', models.URLField(help_text='Link to the application page.')),
                ('post_type', models.CharField(choices=[('attachment', 'Attachment'), ('internship', 'Internship')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.attachee')),
                ('attachment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.attachmentpost')),
            ],
            options={
                'unique_together': {('attachee', 'attachment_post')},
            },
        ),
    ]
