# Generated by Django 6.0.5 on 2026-06-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentpost',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
