# Generated by Django 6.0.5 on 2026-06-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('image', models.ImageField(default='default-avatar.jpg', upload_to='testimonials_photos/')),
            ],
        ),
    ]
