# Generated by Django 6.0.5 on 2026-06-04 08:07

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE')),
                ('location', models.CharField(max_length=200)),
                ('description', models.CharField(choices=[('single_room', 'Single Room'), ('double_room', 'Double Room'), ('bed_sitter', 'Bed Sitter'), ('hostel', 'Hostel')], default='single_room', max_length=255)),
                ('total_rooms', models.PositiveIntegerField(default=1)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='house_photos/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('single_room', 'Single Room'), ('double_room', 'Double Room'), ('bed_sitter', 'Bed Sitter'), ('hostel', 'Hostel')], default='single_room', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('is_booked', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='housing.house')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('approaved', 'Approaved')], default='pending', max_length=20)),
                ('attachee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.attachee')),
                ('house_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.house')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.room')),
            ],
        ),
    ]
