# Generated by Django 6.0.5 on 2026-06-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
